-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 10:17:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gkei_mail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gkei_mail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gkei_mail` DEFAULT CHARACTER SET utf8 ;
USE `gkei_mail` ;

-- -----------------------------------------------------
-- Table `gkei_mail`.`AddressType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`AddressType` (
  `AddressTypeID` INT NOT NULL AUTO_INCREMENT,
  `AddressTypeName` VARCHAR(45) NOT NULL,
  `BuiltInType` VARCHAR(45) NOT NULL,
  `SuperTypeID` INT NULL,
  UNIQUE INDEX `AddressTypeID_UNIQUE` (`AddressTypeID` ASC) VISIBLE,
  INDEX `fk_AddressType_AddressType_idx` (`SuperTypeID` ASC) VISIBLE,
  PRIMARY KEY (`AddressTypeID`),
  CONSTRAINT `fk_AddressType_AddressType`
    FOREIGN KEY (`SuperTypeID`)
    REFERENCES `gkei_mail`.`AddressType` (`AddressTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkei_mail`.`PurposeType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`PurposeType` (
  `PurposeTypeID` INT NOT NULL,
  `PurposeTypeName` VARCHAR(45) NOT NULL,
  `MashiMashiType` VARCHAR(45) NOT NULL,
  `BuiltInType` VARCHAR(45) NOT NULL,
  `SuperTypeID` INT NULL,
  PRIMARY KEY (`PurposeTypeID`),
  UNIQUE INDEX `ContentCategoryID_UNIQUE` (`PurposeTypeID` ASC) VISIBLE,
  INDEX `fk_ContentType_ContentType1_idx` (`SuperTypeID` ASC) VISIBLE,
  CONSTRAINT `fk_ContentType_ContentType1`
    FOREIGN KEY (`SuperTypeID`)
    REFERENCES `gkei_mail`.`PurposeType` (`PurposeTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkei_mail`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`User` (
  `UserID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkei_mail`.`Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`Template` (
  `TemplateID` INT NOT NULL,
  `TemplateName` VARCHAR(45) NOT NULL,
  `TemplateContent` VARCHAR(1000) NOT NULL,
  `CreateDate` DATETIME NOT NULL,
  `MashiMashiValue` INT NOT NULL,
  `BuiltInType` VARCHAR(45) NOT NULL,
  `AddressTypeID` INT NOT NULL,
  `PurposeTypeID` INT NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`TemplateID`),
  UNIQUE INDEX `TemplateID_UNIQUE` (`TemplateID` ASC) VISIBLE,
  INDEX `fk_Template_AddressType1_idx` (`AddressTypeID` ASC) VISIBLE,
  INDEX `fk_Template_PurposeType1_idx` (`PurposeTypeID` ASC) VISIBLE,
  INDEX `fk_Template_User1_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `fk_Template_AddressType1`
    FOREIGN KEY (`AddressTypeID`)
    REFERENCES `gkei_mail`.`AddressType` (`AddressTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Template_PurposeType1`
    FOREIGN KEY (`PurposeTypeID`)
    REFERENCES `gkei_mail`.`PurposeType` (`PurposeTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Template_User1`
    FOREIGN KEY (`UserID`)
    REFERENCES `gkei_mail`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkei_mail`.`Jikou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`Jikou` (
  `JikouID` INT NOT NULL,
  `JikouContent` VARCHAR(1000) NOT NULL,
  `BeginMonth` INT NOT NULL,
  `EndMonth` INT NOT NULL,
  PRIMARY KEY (`JikouID`),
  UNIQUE INDEX `JikouID_UNIQUE` (`JikouID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkei_mail`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`Keyword` (
  `KeywordID` INT NOT NULL,
  `KeywordContent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`KeywordID`),
  UNIQUE INDEX `KeywordID_UNIQUE` (`KeywordID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkei_mail`.`TemplateKeyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkei_mail`.`TemplateKeyword` (
  `TemplateKeywordID` INT NOT NULL,
  `KeywordID` INT NOT NULL,
  `TemplateID` INT NOT NULL,
  INDEX `fk_TemplateKeyword_Keyword1_idx` (`KeywordID` ASC) VISIBLE,
  INDEX `fk_TemplateKeyword_Template1_idx` (`TemplateID` ASC) VISIBLE,
  PRIMARY KEY (`TemplateKeywordID`),
  UNIQUE INDEX `TemplateKeywordID_UNIQUE` (`TemplateKeywordID` ASC) VISIBLE,
  CONSTRAINT `fk_TemplateKeyword_Keyword1`
    FOREIGN KEY (`KeywordID`)
    REFERENCES `gkei_mail`.`Keyword` (`KeywordID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TemplateKeyword_Template1`
    FOREIGN KEY (`TemplateID`)
    REFERENCES `gkei_mail`.`Template` (`TemplateID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
